# Delay (in ticks), after which the data for all online players will be renewed.
renewTime: 20

# Selected from below options.
lang: 'en'

# Enable bStats for PlayerManager or not (will collect the player count, renew time and the language)
bStats: true


en:
  could-not-save-file: '&cCould not save file &6%name% &c!'
  no-permissions: '&cInsufficient permissions!'
  too-little-arguments: '&cToo little arguments for command &6%command%&c! Usage: &b%usage%'
  too-many-arguments: '&cToo many arguments for command &6%command%&c! Usage: &b%usage%'
  cant-console: '&cYou can''t use this from console!'
  no-such-player: '&cThere''s no player &6%player% &conline!'
  no-player-data: '&cThere''s no file that stores data of player &6%player%&c!'
ru:
  could-not-save-file: '&cНе получилось сохранить &6%name% &c!'
  no-permissions: '&cНедостаточно прав!'
  too-little-arguments: '&cСлишком мало аргументов для команды &6%command%&c! Использование: &b%usage%'
  too-many-arguments: '&cСлишком много аргументов для команды &6%command%&c! Использование: &b%usage%'
  cant-console: '&cЭта команда не может быть использована консолью!'
  no-such-player: '&cИгрок &6%player% &cне в сети или не найден!'
  no-player-data: '&cНе найдено файла, хранящего данные игрока &6%player%&c!'
de:
  could-not-save-file: '&cFehler beim Speichern der Datei &6%name% &c!'
  no-permissions: '&cKeine Berechtigung!'
  too-little-arguments: '&cZu wenig Parameter für Befehl &6%command%&c! Benutzung: &b%usage%'
  too-many-arguments: '&cZu viele Parameter für Befehl &6%command%&c! Benutzung: &b%usage%'
  cant-console: '&cDieser Befehl kann nur von Spielern ausgeführt werden!'
  no-such-player: '&cDer Spieler &6%player% &cist nicht online!'
  no-player-data: '&cKeine Datei gefunden die Informationen über Spieler &6%player%&c enthält!'
